version: '3'

services:
  frontend:
    build:
      context: ./frontend
      args:
        SERVER_SIDE_BACKEND_BASE_URL: http://backend:3000/api
        NEXT_PUBLIC_BACKEND_BASE_URL: http://localhost:3000/api
        NEXT_PUBLIC_FRONTEND_BASE_URL: http://localhost:80
        NEXT_PUBLIC_FRONTEND_BASE_HTTP_URL: http://localhost:80
    command: npm run dev
    volumes:
      - ./frontend:/code
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - SERVER_SIDE_BACKEND_BASE_URL=http://backend:3000/api
      - NEXT_PUBLIC_BACKEND_BASE_URL=http://localhost:3000/api
      - NEXT_PUBLIC_FRONTEND_BASE_URL=http://localhost:80
      - NEXT_PUBLIC_FRONTEND_BASE_HTTP_URL=http://localhost:80

  backend:
    build: ./backend
    command: bash -c "poetry run uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload"
    volumes:
      - ./backend:/code
    ports:
      - "3000:3000"
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - OPENAI_API_KEY=${OPENAI_KEY}
    depends_on:
      - db
      - pgadmin
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  embedding-indexer:
    build:
      context: ./embedding-indexer
      args:
        - GOOS=darwin
    image: embedding-indexer:latest
    command: ./index
    ports:
      - "6000:6000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - OPENAI_KEY=${OPENAI_KEY}

volumes:
  pgadmin-data:
  postgres_data:
