version: "3"

services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    command: bash -c "poetry run alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload"
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - APP_ENV=development

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db